title: desterhuizen
email: info@desterhuizen.uk
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog and website.
baseurl: ""
url: "https://desterhuizen.uk"

markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
