title: "Dawid Esterhuizen"
description: "Cloud security governance at organisation scale. OSCE3, OSCP, OSDA."
url: "https://desterhuizen.uk"
permalink: /writing/:title/
markdown: kramdown

# Build settings
exclude:
  - example.html
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
